make_diverging_palette <- function(x) {
  lim <- max(abs(x), na.rm = TRUE)
  if (!is.finite(lim) || lim == 0) lim <- 1
  leaflet::colorNumeric(
    palette = colorRampPalette(c("#264653", "#2a9d8f", "#edf2fb", "#f3722c", "#f94144"))(256),
    domain = c(-lim, lim),
    na.color = "#dddddd"
  )
}

make_sequential_palette <- function(x) {
  rng <- range(x, na.rm = TRUE)
  if (!all(is.finite(rng))) rng <- c(0, 1)
  if (rng[[1]] == rng[[2]]) rng[[2]] <- rng[[2]] + 1
  leaflet::colorNumeric(
    palette = colorRampPalette(c("#f7fbff", "#c6dbef", "#6baed6", "#2171b5", "#08306b"))(256),
    domain = rng,
    na.color = "#dddddd"
  )
}

metric_is_diverging <- function(metric_name) {
  stringr::str_detect(metric_name, "^delta_|increase|becomes_unreachable")
}

metric_label <- function(metric_name) {
  dplyr::case_match(
    metric_name,
    "avg_weighted_travel_time_penalized" ~ "Weighted average travel time (minutes)",
    "share_unreachable_weighted" ~ "Weighted unreachable share",
    "share_accessible_45min_weighted" ~ "Weighted share accessible within 45 minutes",
    "share_accessible_60min_weighted" ~ "Weighted share accessible within 60 minutes",
    "delta_avg_weighted_travel_time_penalized" ~ "Change in weighted average travel time (minutes)",
    "delta_pct_weighted_travel_time_penalized" ~ "Percent change in weighted average travel time",
    "delta_unreachable_share_weighted" ~ "Change in weighted unreachable share",
    "share_weight_increase_gt_10" ~ "Share of OD weight with increase above 10 minutes",
    "share_weight_becomes_unreachable" ~ "Share of OD weight becoming unreachable",
    "origin_total_weight" ~ "Total outgoing OD weight",
    "destination_total_weight" ~ "Total incoming OD weight",
    .default = metric_name
  )
}

metric_description <- function(metric_name) {
  dplyr::case_match(
    metric_name,
    "avg_weighted_travel_time_penalized" ~ "Average transit travel time from each origin tract, weighted by the OD importance in the survey. Unreachable OD pairs receive the configured penalty time.",
    "share_unreachable_weighted" ~ "Share of survey OD weight that cannot be completed within the routing settings for the selected period and time window.",
    "share_accessible_45min_weighted" ~ "Share of survey OD weight reachable within 45 minutes from each origin tract.",
    "share_accessible_60min_weighted" ~ "Share of survey OD weight reachable within 60 minutes from each origin tract.",
    "delta_avg_weighted_travel_time_penalized" ~ "Change in weighted average travel time between two periods. Positive values mean trips became slower.",
    "delta_pct_weighted_travel_time_penalized" ~ "Percent change in weighted average travel time between two periods.",
    "delta_unreachable_share_weighted" ~ "Change in the share of weighted OD demand that is unreachable between two periods.",
    "share_weight_increase_gt_10" ~ "Share of weighted OD demand whose travel time increased by more than 10 minutes between two periods.",
    "share_weight_becomes_unreachable" ~ "Share of weighted OD demand that changed from reachable to unreachable between two periods.",
    "origin_total_weight" ~ "Total survey based OD weight generated by each origin tract under the selected survey scenario.",
    "destination_total_weight" ~ "Total survey based OD weight attracted to each destination tract under the selected survey scenario.",
    .default = metric_name
  )
}

metric_short_title <- function(metric_name) {
  dplyr::case_match(
    metric_name,
    "avg_weighted_travel_time_penalized" ~ "Weighted average travel time",
    "share_unreachable_weighted" ~ "Weighted unreachable share",
    "share_accessible_45min_weighted" ~ "Weighted share accessible within 45 minutes",
    "share_accessible_60min_weighted" ~ "Weighted share accessible within 60 minutes",
    "delta_avg_weighted_travel_time_penalized" ~ "Change in weighted average travel time",
    "delta_pct_weighted_travel_time_penalized" ~ "Percent change in weighted average travel time",
    "delta_unreachable_share_weighted" ~ "Change in weighted unreachable share",
    "share_weight_increase_gt_10" ~ "Share with increase above 10 minutes",
    "share_weight_becomes_unreachable" ~ "Share becoming unreachable",
    "origin_total_weight" ~ "Origin OD importance",
    "destination_total_weight" ~ "Destination OD importance",
    .default = metric_label(metric_name)
  )
}

attach_single_visible_legend <- function(map_obj, group_values, default_group) {
  js <- sprintf(
    "function(el, x) {
       var groups = %s;
       var defaultGroup = %s;
       function getLegends() {
         return el.querySelectorAll('.legend.leaflet-control');
       }
       function showLegend(name) {
         var legends = getLegends();
         groups.forEach(function(g, i) {
           if (legends[i]) {
             legends[i].style.display = (g === name) ? 'block' : 'none';
           }
         });
       }
       setTimeout(function() { showLegend(defaultGroup); }, 120);
       this.on('baselayerchange', function(e) { showLegend(e.name); });
     }",
    jsonlite::toJSON(as.list(group_values), auto_unbox = TRUE),
    jsonlite::toJSON(default_group, auto_unbox = TRUE)
  )
  htmlwidgets::onRender(map_obj, js)
}

format_popup_table <- function(df, popup_cols) {
  purrr::pmap_chr(df %>% sf::st_drop_geometry() %>% dplyr::select(all_of(popup_cols)), function(...) {
    vals <- list(...)
    paste0(purrr::imap_chr(vals, ~ paste0("<b>", .y, "</b>: ", .x)), collapse = "<br>")
  })
}

is_valid_zone_id_for_unit <- function(zone_id, unit) {
  zone_chr <- as.character(zone_id)
  if (length(zone_chr) == 0) return(logical())
  unit_use <- tolower(as.character(unit %||% "tract"))
  if (unit_use %in% c("zip", "zipcode", "zcta")) {
    return(!is.na(zone_chr) & stringr::str_detect(zone_chr, "^\\d{5}$"))
  }
  if (unit_use %in% c("tract", "census_tract")) {
    return(!is.na(zone_chr) & stringr::str_detect(zone_chr, "^\\d{11}$"))
  }
  !is.na(zone_chr) & nzchar(zone_chr)
}

ensure_origin_id_column <- function(sf_obj, unit) {
  if ("origin_id" %in% names(sf_obj)) {
    sf_obj$origin_id <- standardize_zone_id(sf_obj$origin_id, unit)
    return(sf_obj)
  }

  fallback_col <- dplyr::first(intersect(c("zone_id", "GEOID", "geoid", "tract_id"), names(sf_obj)))
  if (is.null(fallback_col) || !nzchar(fallback_col)) {
    stop("Map input is missing an origin id column. Expected `origin_id` or a compatible fallback (`zone_id`, `GEOID`, `tract_id`).", call. = FALSE)
  }

  sf_obj %>% dplyr::mutate(origin_id = standardize_zone_id(.data[[fallback_col]], unit))
}
build_metric_map <- function(sf_obj, county_outlines, metric_col, group_col, popup_cols, output_path, default_group = NULL) {
  group_values <- sf_obj %>% sf::st_drop_geometry() %>% dplyr::pull(.data[[group_col]]) %>% unique() %>% sort()
  if (length(group_values) == 0) return(invisible(NULL))
  if (is.null(default_group) || !default_group %in% group_values) default_group <- group_values[[1]]

  pal_fun <- if (metric_is_diverging(metric_col)) make_diverging_palette else make_sequential_palette
  global_values <- sf_obj %>% sf::st_drop_geometry() %>% dplyr::pull(.data[[metric_col]])
  pal <- pal_fun(global_values)
  map_obj <- leaflet::leaflet(options = leaflet::leafletOptions(zoomControl = TRUE)) %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron)

  for (grp in group_values) {
    df <- sf_obj %>% dplyr::filter(.data[[group_col]] == grp)
    if (nrow(df) == 0) next

    df <- df %>% mutate(map_value = .data[[metric_col]])
    popup_html <- format_popup_table(df, popup_cols)

    map_obj <- map_obj %>%
      leaflet::addPolygons(
        data = df,
        group = grp,
        fillColor = ~ pal(map_value),
        fillOpacity = 0.75,
        color = "white",
        weight = 0.8,
        popup = popup_html,
        highlightOptions = leaflet::highlightOptions(weight = 2, color = "#111111", bringToFront = TRUE)
      ) %>%
      leaflet::addLegend(
        pal = pal,
        values = global_values,
        title = metric_label(metric_col),
        position = "bottomright",
        na.label = "No data",
        group = grp
      )
  }

  map_obj <- map_obj %>%
    leaflet::addPolygons(data = county_outlines, fill = FALSE, color = "black", weight = 1.5, group = "County outlines") %>%
    leaflet::addLayersControl(baseGroups = group_values, overlayGroups = c("County outlines"), options = leaflet::layersControlOptions(collapsed = FALSE))

  hide_groups <- setdiff(group_values, default_group)
  if (length(hide_groups) > 0) map_obj <- map_obj %>% leaflet::hideGroup(hide_groups)

  map_obj <- attach_single_visible_legend(map_obj, group_values, default_group)
  htmlwidgets::saveWidget(map_obj, output_path, selfcontained = FALSE, libdir = paste0(tools::file_path_sans_ext(output_path), "_files"))
  invisible(map_obj)
}

build_od_marginal_sf <- function(tracts_sf, marginals_df, id_col, value_col, unit = "tract") {
  if (!id_col %in% names(marginals_df)) {
    fallback_candidates <- c(
      "zone_id",
      "GEOID",
      "geoid",
      "tract_id",
      if (id_col == "origin_id") c("origin", "from_id") else character(),
      if (id_col == "destination_id") c("destination", "to_id") else character()
    )
    fallback_col <- dplyr::first(intersect(fallback_candidates, names(marginals_df)))
    if (is.null(fallback_col) || !nzchar(fallback_col)) {
      stop(
        paste0(
          "OD marginal data is missing `", id_col,
          "`. Expected `", id_col,
          "` or one of: ", paste(fallback_candidates, collapse = ", "), "."
        ),
        call. = FALSE
      )
    }
    marginals_df <- marginals_df %>% dplyr::mutate(!!id_col := .data[[fallback_col]])
  }

  marginals_df <- marginals_df %>% dplyr::mutate(!!id_col := standardize_zone_id(.data[[id_col]], unit))

  tracts_sf %>%
    left_join(marginals_df, by = setNames(id_col, "GEOID")) %>%
    mutate(
      !!id_col := standardize_zone_id(.data$GEOID, unit),
      scenario_id = as.character(scenario_id),
      !!value_col := safe_numeric(.data[[value_col]])
    )
}

build_od_lines_sf <- function(top_pairs_df, zone_centroids_sf, zones_sf, max_pairs = 500) {
  tract_points <- zone_centroids_sf %>%
    sf::st_transform(4326) %>%
    mutate(
      tract_id = as.character(zone_id),
      lon = sf::st_coordinates(.)[, 1],
      lat = sf::st_coordinates(.)[, 2]
    ) %>%
    sf::st_drop_geometry() %>%
    select(tract_id, lon, lat)

  tract_names <- zones_sf %>% sf::st_drop_geometry() %>% transmute(tract_id = as.character(zone_id), tract_name = as.character(zone_name))

  top_use <- top_pairs_df %>%
    mutate(
      origin_id = as.character(origin_id),
      destination_id = as.character(destination_id),
      scenario_id = as.character(scenario_id)
    ) %>%
    filter(!is.na(scenario_id), nzchar(scenario_id)) %>%
    mutate(weight_use = dplyr::coalesce(weight_sum_adjusted, weight_sum)) %>%
    group_by(scenario_id) %>%
    arrange(desc(weight_use), .by_group = TRUE) %>%
    mutate(rank = row_number()) %>%
    filter(rank <= max_pairs) %>%
    ungroup()

  lines_df <- top_use %>%
    left_join(tract_points %>% rename(origin_id = tract_id, origin_lon = lon, origin_lat = lat), by = "origin_id") %>%
    left_join(tract_points %>% rename(destination_id = tract_id, destination_lon = lon, destination_lat = lat), by = "destination_id") %>%
    left_join(tract_names %>% rename(origin_id = tract_id, origin_name = tract_name), by = "origin_id") %>%
    left_join(tract_names %>% rename(destination_id = tract_id, destination_name = tract_name), by = "destination_id") %>%
    filter(!is.na(origin_lon), !is.na(origin_lat), !is.na(destination_lon), !is.na(destination_lat))

  if (nrow(lines_df) == 0) {
    return(NULL)
  }

  weights_by_scenario <- lines_df %>% group_by(scenario_id) %>% summarise(max_weight = max(weight_use, na.rm = TRUE), .groups = "drop")
  lines_df <- lines_df %>%
    left_join(weights_by_scenario, by = "scenario_id") %>%
    mutate(
      line_weight_base = dplyr::if_else(is.finite(max_weight) & max_weight > 0, 1 + 6 * sqrt(weight_use / max_weight), 2),
      geometry = purrr::pmap(
        list(origin_lon, origin_lat, destination_lon, destination_lat),
        function(olon, olat, dlon, dlat) sf::st_linestring(matrix(c(olon, dlon, olat, dlat), ncol = 2))
      )
    )

  sf::st_as_sf(lines_df, sf_column_name = "geometry", crs = 4326) %>%
    select(scenario_id, scenario_label, time_bin, rank, weight_sum, weight_sum_adjusted, weight_use, origin_id, destination_id, origin_name, destination_name, line_weight_base, geometry)
}


build_od_line_map <- function(lines_sf, county_outlines, output_path, default_group = NULL, default_top_n = 100) {
  if (is.null(lines_sf) || nrow(lines_sf) == 0) return(invisible(NULL))

  group_values <- sort(unique(as.character(lines_sf$scenario_id)))
  if (length(group_values) == 0) return(invisible(NULL))
  if (is.null(default_group) || !default_group %in% group_values) default_group <- group_values[[1]]

  max_rank <- max(lines_sf$rank, na.rm = TRUE)
  if (!is.finite(max_rank) || max_rank < 1) max_rank <- 1
  default_top_n <- max(1, min(default_top_n, max_rank))

  map_obj <- leaflet::leaflet(options = leaflet::leafletOptions(zoomControl = TRUE)) %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron)

  for (grp in group_values) {
    df <- lines_sf %>% dplyr::filter(.data$scenario_id == grp)
    if (nrow(df) == 0) next

    popup_html <- format_popup_table(
      df %>% dplyr::mutate(
        weight_use = round(.data$weight_use, 3),
        rank = as.integer(.data$rank)
      ),
      c("scenario_id", "rank", "origin_name", "destination_name", "weight_use")
    )

    map_obj <- map_obj %>%
      leaflet::addPolylines(
        data = df,
        group = grp,
        color = "#c0392b",
        weight = ~ line_weight_base,
        opacity = 0.8,
        popup = popup_html,
        layerId = ~ paste0(as.character(scenario_id), "__", as.integer(rank)),
        options = leaflet::pathOptions(
          className = paste0("od-line od-line-", grp)
        ),
        highlightOptions = leaflet::highlightOptions(
          weight = 7,
          color = "#7f0000",
          bringToFront = TRUE
        )
      )
  }

  slider_html <- htmltools::HTML(
    paste0(
      "<div id='od-topn-control' style='background: white; padding: 10px 12px; border-radius: 6px; box-shadow: 0 1px 5px rgba(0,0,0,0.35); width: 220px;'>",
      "<div style='font-weight: 600; margin-bottom: 6px;'>OD lines shown</div>",
      "<input id='od-topn-range' type='range' min='1' max='", max_rank, "' step='1' value='", default_top_n, "' style='width: 180px;'>",
      "<div style='margin-top: 4px;'>Top <span id='od-topn-value'>", default_top_n, "</span> OD pairs</div>",
      "</div>"
    )
  )

  map_obj <- map_obj %>%
    leaflet::addPolygons(
      data = county_outlines,
      fill = FALSE,
      color = "black",
      weight = 1.5,
      group = "County outlines"
    ) %>%
    leaflet::addLayersControl(
      baseGroups = group_values,
      overlayGroups = c("County outlines"),
      options = leaflet::layersControlOptions(collapsed = FALSE)
    ) %>%
    leaflet::addControl(slider_html, position = "topright")

  hide_groups <- setdiff(group_values, default_group)
  if (length(hide_groups) > 0) {
    map_obj <- map_obj %>% leaflet::hideGroup(hide_groups)
  }

  js <- sprintf(
    "function(el, x) {
       var map = this;
       map._activeOdGroup = %s;

       function parseLayerInfo(layer) {
         if (!layer || !layer.options) return null;

         var rawId = null;
         if (layer.options.layerId !== undefined && layer.options.layerId !== null) rawId = layer.options.layerId;
         if ((rawId === null || rawId === undefined || rawId === '') && layer.options.attribution) rawId = layer.options.attribution;
         if (rawId === null || rawId === undefined || rawId === '') return null;

         var id = String(rawId);
         var m = id.match(/^(.*)__([0-9]+)$/);
         if (!m) return null;

         return {
           scenario_id: m[1],
           rank: parseInt(m[2], 10)
         };
       }

       function setLayerVisible(layer, visible) {
         if (layer && layer._odBaseWeight === undefined) {
           var firstWeight = 2;
           if (layer.options && layer.options.weight !== undefined) {
             firstWeight = parseFloat(layer.options.weight);
             if (!isFinite(firstWeight)) firstWeight = 2;
           }
           layer._odBaseWeight = firstWeight;
         }
         var baseWeight = layer._odBaseWeight || 2;

         if (layer.setStyle) {
           layer.setStyle({
             opacity: visible ? 0.8 : 0.0,
             weight: visible ? baseWeight : 0.1
           });
         }

         if (layer.getElement && layer.getElement()) {
           var elPath = layer.getElement();
           elPath.style.display = visible ? '' : 'none';
           elPath.style.pointerEvents = visible ? 'auto' : 'none';
         }

         if (!visible && layer.closePopup) {
           try { layer.closePopup(); } catch (e) {}
         }
       }

       function visitLayers(layer, fn) {
         if (!layer) return;
         if (layer.eachLayer && !layer.getLatLngs) {
           layer.eachLayer(function(child) { visitLayers(child, fn); });
           return;
         }
         fn(layer);
       }

       function updateLines() {
         var slider = el.querySelector('#od-topn-range');
         var label = el.querySelector('#od-topn-value');
         if (!slider) return;

         var topN = parseInt(slider.value || '100', 10);
         if (!isFinite(topN)) topN = 100;
         if (label) label.textContent = topN;

         map.eachLayer(function(layer) {
           visitLayers(layer, function(child) {
             var info = parseLayerInfo(child);
             if (!info) return;
             var keep = (String(info.scenario_id) === String(map._activeOdGroup)) && (info.rank <= topN);
             setLayerVisible(child, keep);
           });
         });
       }

       var slider = el.querySelector('#od-topn-range');
       if (slider) {
         slider.addEventListener('input', updateLines);
         slider.addEventListener('change', updateLines);
       }

       map.on('baselayerchange', function(e) {
         map._activeOdGroup = e.name;
         updateLines();
       });

       setTimeout(updateLines, 250);
     }",
    jsonlite::toJSON(default_group, auto_unbox = TRUE)
  )

  map_obj <- htmlwidgets::onRender(map_obj, js)
  htmlwidgets::saveWidget(
    map_obj,
    output_path,
    selfcontained = FALSE,
    libdir = paste0(tools::file_path_sans_ext(output_path), "_files")
  )
  invisible(map_obj)
}

write_maps_index <- function(index_entries, output_path, title_text) {
  section_order <- c("Accessibility level maps", "Accessibility change maps", "OD importance maps")
  section_blocks <- purrr::map_chr(section_order, function(section_name) {
    df <- index_entries %>% filter(section == section_name)
    if (nrow(df) == 0) return("")
    items <- paste0(
      "<div class='map-item'><div class='map-link'><a href='", basename(df$file), "'>", df$title, "</a></div><div class='map-desc'>", df$description, "</div></div>",
      collapse = "\n"
    )
    paste0("<section><h2>", section_name, "</h2>", items, "</section>")
  })

  html <- paste0(
    "<!DOCTYPE html><html><head><meta charset='utf-8'><title>", title_text, "</title>",
    "<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:1100px;margin:32px auto;padding:0 20px;line-height:1.45;color:#222}h1{margin-bottom:8px}p.lead{margin-top:0;color:#555}section{margin-top:28px;padding-top:8px;border-top:1px solid #e5e5e5}.map-item{padding:14px 0}.map-link a{font-size:18px;font-weight:600;color:#0b57d0;text-decoration:none}.map-link a:hover{text-decoration:underline}.map-desc{margin-top:6px;color:#444;max-width:900px}</style>",
    "</head><body><h1>", title_text, "</h1>",
    "<p class='lead'>Each map below is grouped by type. The note under each link explains what the map measures so you can choose the right view quickly.</p>",
    paste0(section_blocks, collapse = "\n"),
    "</body></html>"
  )
  writeLines(html, output_path)
}

make_all_interactive_maps <- function(cfg) {
  county_outlines <- sf::st_read(file.path(cfg$paths$geography_dir, "county_outlines.gpkg"), quiet = TRUE)
  tracts_sf <- sf::st_read(file.path(cfg$paths$geography_dir, "analysis_zones.gpkg"), quiet = TRUE) %>% dplyr::rename(GEOID = zone_id, NAME = zone_name)
  tract_centroids <- sf::st_read(file.path(cfg$paths$geography_dir, "analysis_zone_centroids.gpkg"), quiet = TRUE)
  analysis_zones <- sf::st_read(file.path(cfg$paths$geography_dir, "analysis_zones.gpkg"), quiet = TRUE)
  metrics_sf <- sf::st_read(file.path(cfg$paths$accessibility_dir, "tract_period_metrics.gpkg"), quiet = TRUE)
  comparisons_sf <- sf::st_read(file.path(cfg$paths$accessibility_dir, "tract_period_comparisons.gpkg"), quiet = TRUE)
  od_origin <- read_csv_guess(file.path(cfg$paths$od_dir, "od_marginals_origin.csv")) %>% mutate(origin_id = as.character(origin_id))
  od_destination <- read_csv_guess(file.path(cfg$paths$od_dir, "od_marginals_destination.csv")) %>% mutate(destination_id = as.character(destination_id))
  od_top_pairs <- read_csv_guess(file.path(cfg$paths$od_dir, "top_od_pairs.csv")) %>% mutate(origin_id = as.character(origin_id), destination_id = as.character(destination_id))

  fs::dir_create(cfg$paths$maps_dir)

  period_metrics <- cfg$map$period_metrics %||% c("avg_weighted_travel_time_penalized", "share_unreachable_weighted", "share_accessible_45min_weighted")
  comparison_metrics <- cfg$map$comparison_metrics %||% c("delta_avg_weighted_travel_time_penalized", "delta_pct_weighted_travel_time_penalized", "delta_unreachable_share_weighted", "share_weight_increase_gt_10", "share_weight_becomes_unreachable")
  od_top_pairs_max <- cfg$map$od_top_pairs_max %||% 500
  od_top_pairs_default <- cfg$map$od_top_pairs_default %||% 100

  index_entries <- tibble(file = character(), title = character(), description = character(), section = character())

  valid_zone_ids <- analysis_zones %>%
    sf::st_drop_geometry() %>%
    transmute(origin_id = standardize_zone_id(zone_id, cfg$geography$analysis_unit)) %>%
    pull(origin_id) %>%
    unique()

  metrics_sf <- ensure_origin_id_column(metrics_sf, cfg$geography$analysis_unit) %>%
    mutate(
      scenario_id = as.character(scenario_id),
      time_window_id = as.character(time_window_id),
      period_id = as.character(period_id)
    ) %>%
    filter(
      origin_id %in% valid_zone_ids,
      is_valid_zone_id_for_unit(origin_id, cfg$geography$analysis_unit),
      !is.na(scenario_id),
      !is.na(time_window_id),
      !is.na(period_id)
    ) %>%
    mutate(layer_group = paste0(time_window_id, " | ", period_id, " | ", scenario_id))
  default_period <- metrics_sf %>% sf::st_drop_geometry() %>% dplyr::filter(time_window_id == (cfg$map$default_time_window_id %||% first(time_window_id))) %>% dplyr::slice(1) %>% dplyr::pull(layer_group)
  if (length(default_period) == 0) default_period <- metrics_sf %>% sf::st_drop_geometry() %>% dplyr::slice(1) %>% dplyr::pull(layer_group)

  for (metric_col in period_metrics) {
    if (!metric_col %in% names(metrics_sf)) next
    out_path <- file.path(cfg$paths$maps_dir, paste0(metric_col, ".html"))
    build_metric_map(
      sf_obj = metrics_sf,
      county_outlines = county_outlines,
      metric_col = metric_col,
      group_col = "layer_group",
      popup_cols = c("NAME", "origin_id", "period_id", "time_window_id", "scenario_id", metric_col),
      output_path = out_path,
      default_group = default_period
    )
    index_entries <- bind_rows(index_entries, tibble(file = out_path, title = metric_short_title(metric_col), description = metric_description(metric_col), section = "Accessibility level maps"))
  }

  comparisons_sf <- ensure_origin_id_column(comparisons_sf, cfg$geography$analysis_unit) %>%
    mutate(
      scenario_id = as.character(scenario_id),
      time_window_id = as.character(time_window_id),
      comparison_id = as.character(comparison_id)
    ) %>%
    filter(
      origin_id %in% valid_zone_ids,
      is_valid_zone_id_for_unit(origin_id, cfg$geography$analysis_unit),
      !is.na(scenario_id),
      !is.na(time_window_id),
      !is.na(comparison_id)
    ) %>%
    mutate(layer_group = paste0(time_window_id, " | ", comparison_id, " | ", scenario_id))
  default_comparison_id <- cfg$map$default_comparison_id %||% (comparisons_sf %>% sf::st_drop_geometry() %>% dplyr::slice(1) %>% dplyr::pull(comparison_id))
  default_compare <- comparisons_sf %>% sf::st_drop_geometry() %>% dplyr::filter(comparison_id == default_comparison_id, time_window_id == (cfg$map$default_time_window_id %||% first(time_window_id))) %>% dplyr::slice(1) %>% dplyr::pull(layer_group)
  if (length(default_compare) == 0) default_compare <- comparisons_sf %>% sf::st_drop_geometry() %>% dplyr::slice(1) %>% dplyr::pull(layer_group)

  for (metric_col in comparison_metrics) {
    if (!metric_col %in% names(comparisons_sf)) next
    out_path <- file.path(cfg$paths$maps_dir, paste0(metric_col, ".html"))
    build_metric_map(
      sf_obj = comparisons_sf,
      county_outlines = county_outlines,
      metric_col = metric_col,
      group_col = "layer_group",
      popup_cols = c("NAME", "origin_id", "comparison_id", "time_window_id", "scenario_id", metric_col),
      output_path = out_path,
      default_group = default_compare
    )
    index_entries <- bind_rows(index_entries, tibble(file = out_path, title = metric_short_title(metric_col), description = metric_description(metric_col), section = "Accessibility change maps"))
  }

  origin_sf <- build_od_marginal_sf(tracts_sf, od_origin, "origin_id", "origin_total_weight", unit = cfg$geography$analysis_unit) %>%
    mutate(
      scenario_id = as.character(scenario_id)
    ) %>%
    filter(
      origin_id %in% valid_zone_ids,
      is_valid_zone_id_for_unit(origin_id, cfg$geography$analysis_unit),
      !is.na(scenario_id)
    ) %>%
    mutate(layer_group = scenario_id)
  destination_sf <- build_od_marginal_sf(tracts_sf, od_destination, "destination_id", "destination_total_weight", unit = cfg$geography$analysis_unit) %>%
    mutate(
      scenario_id = as.character(scenario_id)
    ) %>%
    filter(
      destination_id %in% valid_zone_ids,
      is_valid_zone_id_for_unit(destination_id, cfg$geography$analysis_unit),
      !is.na(scenario_id)
    ) %>%
    mutate(layer_group = scenario_id)
  default_od_group <- cfg$map$default_time_window_id %||% (origin_sf %>% sf::st_drop_geometry() %>% dplyr::slice(1) %>% dplyr::pull(layer_group))
  if (!default_od_group %in% unique(origin_sf$layer_group)) default_od_group <- origin_sf %>% sf::st_drop_geometry() %>% dplyr::slice(1) %>% dplyr::pull(layer_group)

  if ("origin_total_weight" %in% names(origin_sf)) {
    out_path <- file.path(cfg$paths$maps_dir, "origin_total_weight.html")
    build_metric_map(origin_sf, county_outlines, "origin_total_weight", "layer_group", c("NAME", "GEOID", "scenario_id", "origin_total_weight"), out_path, default_od_group)
    index_entries <- bind_rows(index_entries, tibble(file = out_path, title = metric_short_title("origin_total_weight"), description = metric_description("origin_total_weight"), section = "OD importance maps"))
  }

  if ("destination_total_weight" %in% names(destination_sf)) {
    out_path <- file.path(cfg$paths$maps_dir, "destination_total_weight.html")
    build_metric_map(destination_sf, county_outlines, "destination_total_weight", "layer_group", c("NAME", "GEOID", "scenario_id", "destination_total_weight"), out_path, default_od_group)
    index_entries <- bind_rows(index_entries, tibble(file = out_path, title = metric_short_title("destination_total_weight"), description = metric_description("destination_total_weight"), section = "OD importance maps"))
  }

  lines_sf <- build_od_lines_sf(od_top_pairs, tract_centroids, analysis_zones, max_pairs = od_top_pairs_max)
  if (!is.null(lines_sf) && nrow(lines_sf) > 0) {
    out_path <- file.path(cfg$paths$maps_dir, "od_top_pairs_interactive.html")
    build_od_line_map(lines_sf, county_outlines, out_path, default_group = default_od_group, default_top_n = od_top_pairs_default)
    index_entries <- bind_rows(index_entries, tibble(file = out_path, title = "Interactive top OD desire lines", description = "Origin and destination centroids are connected for the most important OD pairs in the selected survey scenario. Use the slider to change how many top OD pairs are displayed.", section = "OD importance maps"))
  }

  write_maps_index(index_entries, file.path(cfg$paths$maps_dir, "index.html"), paste0(cfg$project$city_label, " accessibility and OD maps"))
  invisible(index_entries)
}
